#version: 2
#updates:
  # Frontend
#  - package-ecosystem: "npm"
#    directory: "/frontend"
#    schedule:
#      interval: "weekly"
#    versioning-strategy: increase

  # Backend
#  - package-ecosystem: "maven"
#    directory: "/backend"
#    schedule:
#      interval: "weekly"