name: curatix
services:

  # postgreSql
  postgres:
    image: postgres:16-alpine
    container_name: curatix-postgres
    restart: on-failure
    environment:
      - POSTGRES_DB=curatix
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password8080
    ports:
      - "${DOCKER_POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - curatix-network

  # redis
  redis:
    image: redis:alpine
    container_name: curatix-redis
    restart: on-failure
    ports:
      - "${DOCKER_REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - curatix-network

  # elasticsearch
  elasticsearch:
    image: elasticsearch:9.2.3
    container_name: curatix-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - curatix-network

  #zipkin
  zipkin:
    image: openzipkin/zipkin:latest
    container_name: curatix-zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"
    networks:
      - curatix-network

volumes:
  postgres-data:
  redis-data:
  es-data:

networks:
  curatix-network:
    driver: bridge